# Generated by Django 4.1.7 on 2023-03-06 16:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('startingBid', models.FloatField()),
                ('description', models.TextField()),
                ('image', models.URLField(blank=True)),
                ('category', models.CharField(choices=[('TECHNOLOGY', 'Electronics and Technology'), ('FASHION', 'Fashion'), ('COLLECTABLES', ' Arts and Collectables'), ('TOYS', 'Toys'), ('MEDIA', 'Books, Movies, and Music'), ('SPORTS', 'Sporting Goods'), ('HOME', 'Home and Furniture'), ('JEWLERY', 'Jewlery and Watches'), ('HEALTH', 'Health and Beauty'), ('DIY', 'Garden and DIY'), ('UNKNOWN', 'UNKNOWN')], default='UNKNOWN', max_length=16)),
                ('endDate', models.DateTimeField(default=datetime.datetime(2023, 3, 13, 16, 26, 38, 962767, tzinfo=datetime.timezone.utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_auctions', to=settings.AUTH_USER_MODEL)),
                ('watchers', models.ManyToManyField(blank=True, related_name='watching', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_comments', to='project_2_commerce.auction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placed_bids', to='project_2_commerce.auction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_bids', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
