# Generated by Django 4.1.7 on 2023-03-06 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_2_commerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 13, 16, 52, 14, 560612, tzinfo=datetime.timezone.utc)),
        ),
    ]
